[features]
seeds = false
skip-lint = false
[programs.localnet]
betting_app = "Cs6SipyJ7i4Qgw1QaaR2Jmtrbx9c4A7sHa4Kgx9edLHC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/skrzelik/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
